services:
  - type: web
    name: tweet-extractor-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn flask_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: TWEET_EXTRACTOR_URL
        value: https://web-production-68f10.up.railway.app/
        sync: true
        # Aquí tendrás que configurar la URL de tu servicio Railway en el panel de control de Render
      - key: EXTRACTORT_URL
        value: https://extractort-production.up.railway.app/
        sync: true
        # URL del segundo microservicio ExtractorT en Railway
