services:
  - type: web
    name: tweet-extractor-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn flask_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: https://web-production-68f10.up.railway.app/
        sync: false
        # Aquí tendrás que configurar la URL de tu servicio Railway en el panel de control de Render
